spring:
  application:
    name: transaction-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:1111/realms/bank/protocol/openid-connect/certs
  rabbitmq:
    host: "localhost"
    port: 15672
    username: "guest"
    password: "guest"
  config:
    import: optional:configserver:http://localhost:8012
  datasource:
    url: jdbc:postgresql://localhost:4123/transactiondb
    username: transaction
    password: transaction
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081